### ISSUE TITLE
cmake picks charmc from PATH instead of using charmc inside external/install/gnu-x86_64/charm

### ISSUE THREAD

**Issue by nitbhat** [Charmworks/ExaM2M#2]
I saw this issue while setting up ExaM2M on my machine. `charmc` from my PATH was being picked up even though I'd recently built all the external dependent modules. (including charm). 

I see that `CHARM_ROOT` variable can be used to point cmake to the charm installation, but in my opinion, it's best to not pick charm from PATH (even if it means an error is thrown to the user to set CHARM_ROOT)

**Comment by jbakosi** [comment]
Nice catch @nitbhat! I wonder if this can be fixed by simply adding `NO_CMAKE_ENVIRONMENT_PATH` or `NO_SYSTEM_ENVIRONMENT_PATH` to the arguments of cmake's `find_program` calls in `cmake/FindCharm.cmake`. Can you give it a try?

See also https://cmake.org/cmake/help/latest/command/find_program.html.

**Comment by nitbhat** [comment]
@jbakosi: Yes, that was it. `NO_SYSTEM_ENVIRONMENT_PATH` did the trick. I've opened a PR (https://github.com/Charmworks/ExaM2M/pull/3) for that.

**Comment by jbakosi** [comment]
Cool. Thanks, Nitin!
